# Form implementation generated from reading ui file 'newestgui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 450)
        MainWindow.setMinimumSize(QtCore.QSize(425, 450))
        MainWindow.setMaximumSize(QtCore.QSize(425, 450))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(210, 260, 140, 32))
        self.submit_button.setObjectName("submit_button")
        self.Header_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Header_label.setGeometry(QtCore.QRect(130, 10, 141, 16))
        self.Header_label.setObjectName("Header_label")
        self.Candidates_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Candidates_label.setGeometry(QtCore.QRect(150, 100, 111, 21))
        self.Candidates_label.setObjectName("Candidates_label")
        self.Outcome_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Outcome_label.setGeometry(QtCore.QRect(14, 300, 400, 75))
        self.Outcome_label.setText("")
        self.Outcome_label.setObjectName("Outcome_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 50, 170, 30))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ID_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.ID_label.setObjectName("ID_label")
        self.horizontalLayout.addWidget(self.ID_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ID_line = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.ID_line.setObjectName("ID_line")
        self.horizontalLayout.addWidget(self.ID_line)
        self.Can1_radBut = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Can1_radBut.setGeometry(QtCore.QRect(150, 130, 110, 20))
        self.Can1_radBut.setObjectName("Can1_radBut")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Can1_radBut)
        self.Cand2_radBut = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Cand2_radBut.setGeometry(QtCore.QRect(150, 160, 110, 20))
        self.Cand2_radBut.setObjectName("Cand2_radBut")
        self.buttonGroup.addButton(self.Cand2_radBut)
        self.Cand3_radBut = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Cand3_radBut.setGeometry(QtCore.QRect(150, 190, 110, 20))
        self.Cand3_radBut.setObjectName("Cand3_radBut")
        self.buttonGroup.addButton(self.Cand3_radBut)
        self.ResultsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ResultsButton.setGeometry(QtCore.QRect(70, 260, 140, 32))
        self.ResultsButton.setObjectName("ResultsButton")
        self.otherCan_radButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.otherCan_radButton.setGeometry(QtCore.QRect(150, 220, 100, 20))
        self.otherCan_radButton.setObjectName("otherCan_radButton")
        self.buttonGroup.addButton(self.otherCan_radButton)
        self.OtherCan_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.OtherCan_lineEdit.setGeometry(QtCore.QRect(170, 220, 113, 21))
        self.OtherCan_lineEdit.setObjectName("OtherCan_lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 425, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voting Application"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT VOTE"))
        self.Header_label.setText(_translate("MainWindow", "VOTING APPLICATION"))
        self.Candidates_label.setText(_translate("MainWindow", "CANDIDATES"))
        self.ID_label.setText(_translate("MainWindow", "ID"))
        self.Can1_radBut.setText(_translate("MainWindow", "Bianca"))
        self.Cand2_radBut.setText(_translate("MainWindow", "Edward"))
        self.Cand3_radBut.setText(_translate("MainWindow", "Felicia"))
        self.ResultsButton.setText(_translate("MainWindow", "RESULTS"))
        self.otherCan_radButton.setText(_translate("MainWindow", "Other"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
